[package]
name = "crust"
version = "0.2.0"
authors = ["Karl David Hedgren <david@davebay.net>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
chrono = "0.4.7"

[dev-dependencies]
quickcheck = "0.8"
quickcheck_macros = "0.8"